version: "3.3"

services:
    sagzweb:
        image: snipe/snipe-it
        container_name: sagzwebPROD
        hostname: sagzweb
        restart: always
        environment:
            - MAIL_PORT_587_TCP_ADDR=smtp.gmail.com
            - MAIL_PORT_587_TCP_PORT=587
            - MAIL_ENV_FROM_ADDR=clemente.neto@grupozap.com
            - MAIL_ENV_FROM_NAME="Sistema de Inventário GrupoZAP"
            - MAIL_ENV_ENCRYPTION=tcp
            - MAIL_ENV_USERNAME=clemente.neto@grupozap.com
            - MAIL_ENV_PASSWORD=password
            - DB_CONNECTION=mysql
            - DB_HOST=sagzdb
            - DB_DATABASE=snipeit
            - MYSQL_DATABASE=snipeit
            - MYSQL_USER=snipeit
            - MYSQL_PASSWORD=grupozap
            - APP_EN=production
            - APP_DEBUG=false
            - APP_URL=127.0.0.1:80
            - APP_LOCALE=pt 
            - APP_TIMEZONE=America/Sao_Paulo
            - APP_KEY=base64:1/t3C1akUvdu8Iat+1tGVLfdXY1Sjn5zpc4nhPKxAQ8=
        links:
            - sagzdb
        ports:
            - "80:80"
        volumes:
            - /var/lib/docker/volumes/sagp-web-vol/:/var/lib/snipeit
    sagzdb:
        image: mysql:5.6
        container_name: sagzdbPROD
        hostname: sagzdb
        restart: always
        environment:
            - MAIL_PORT_587_TCP_ADDR=smtp.gmail.com
            - MAIL_PORT_587_TCP_PORT=587
            - MAIL_ENV_FROM_ADDR=clemente.neto@grupozap.com
            - MAIL_ENV_FROM_NAME="Sistema de Inventário GrupoZAP"
            - MAIL_ENV_ENCRYPTION=tcp
            - MAIL_ENV_USERNAME=clemente.neto@grupozap.com
            - MAIL_ENV_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=grupozap
            - MYSQL_DATABASE=snipeit
            - MYSQL_USER=snipeit
            - APP_EN=production
            - APP_DEBUG=yes
            - APP_URL=127.0.0.1:8080
            - APP_KEY=base64:1/t3C1akUvdu8Iat+1tGVLfdXY1Sjn5zpc4nhPKxAQ8=
            - MYSQL_PASSWORD=grupozap
        ports:
            - "32769:3306" 
        volumes:
            - /var/lib/docker/volumes/saggpdatabase-vol/:/var/lib/mysql
