version: "3.3"

services:
    tuxweb:
        image: snipe/snipe-it
        container_name: tuxwebPROD
        hostname: tuxweb
        restart: always
        environment:
            - MAIL_PORT_587_TCP_ADDR=smtp.gmail.com
            - MAIL_PORT_587_TCP_PORT=587
            - MAIL_ENV_FROM_ADDR=e-mail@
            - MAIL_ENV_FROM_NAME="Sistema de Inventário"
            - MAIL_ENV_ENCRYPTION=tcp
            - MAIL_ENV_USERNAME=e-mail@
            - MAIL_ENV_PASSWORD=password
            - DB_CONNECTION=mysql
            - DB_HOST=tuxdb
            - DB_DATABASE=snipeit
            - MYSQL_DATABASE=snipeit
            - MYSQL_USER=snipeit
            - MYSQL_PASSWORD=password
            - APP_EN=production
            - APP_DEBUG=false
            - APP_URL=127.0.0.1:80
            - APP_LOCALE=pt 
            - APP_TIMEZONE=America/Sao_Paulo
            - APP_KEY=base64:1/t3C1akUvdu8Iat+1tGVLfdXY1Sjn5zpc4nhPKxAQ8=
        links:
            - tuxdb
        ports:
            - "80:80"
        volumes:
            - /var/lib/docker/volumes/tux-web-vol/:/var/lib/snipeit
    tuxdb:
        image: mysql:5.6
        container_name: tuxdbPROD
        hostname: tuxdb
        restart: always
        environment:
            - MAIL_PORT_587_TCP_ADDR=smtp.gmail.com
            - MAIL_PORT_587_TCP_PORT=587
            - MAIL_ENV_FROM_ADDR=e-mail@
            - MAIL_ENV_FROM_NAME="Sistema de Inventário"
            - MAIL_ENV_ENCRYPTION=tcp
            - MAIL_ENV_USERNAME=e-mail@
            - MAIL_ENV_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=snipeit
            - MYSQL_USER=snipeit
            - APP_EN=production
            - APP_DEBUG=yes
            - APP_URL=127.0.0.1:8080
            - APP_KEY=base64:1/t3C1akUvdu8Iat+1tGVLfdXY1Sjn5zpc4nhPKxAQ8=
            - MYSQL_PASSWORD=password
        ports:
            - "32769:3306" 
        volumes:
            - /var/lib/docker/volumes/tux-database-vol/:/var/lib/mysql
